### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [pqpo/PLock#1]
Hi @pqpo . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by pqpo** [comment]
Thank you, of course you can. But for this project? It's just an Android library.

**Comment by mirzazulfan** [comment]
Thank for your response. I'll make it for this project. If you have an idea please share with me. It would be better for me. Thanks

**Comment by mirzazulfan** [comment]
Hi @pqpo .. I've Designed a logo for your project, tell me if you need anything change i'll fix it. if you like it, i'll send yuo files and pr. Thanks
![plock](https://user-images.githubusercontent.com/36124339/41699630-f156d3b8-754e-11e8-9b1e-c2acfe5f4bd9.png)

**Comment by pqpo** [comment]
Thank you so much, I like the blue one.

**Comment by mirzazulfan** [comment]
@pqpo I'm glad you liked it, you can download all files (.Png .Pdf .Svg .Jpg)  in [Gdrive](https://drive.google.com/drive/folders/1OuYM05bXtrIsGEdenhCGpEfz69VtiA7z)
I've created a pr #2 Please check. Thank you

Best Regard.

**Comment by pqpo** [comment]
Done!
